Olympics/Olympics/Models/AthleteModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Olympics.Models
{
    public class AthleteModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int CountryId { get; set; }

        public string CountryName { get; set; }
        public string SportsNames { get; set; }
        public int SportId { get; set; }
        public bool TeamActivity { get; set; }
        public List<string> Sports { get; set; }
       

    }
}

Olympics/Olympics/Models/CountryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Olympics.Models
{
    public class CountryModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ISO3 { get; set; }
    }
}

Olympics/Olympics/Models/ErrorViewModel.cs
using System;

namespace Olympics.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Olympics/Olympics/Models/ParticipantsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Olympics.Models
{

    public class ParticipantsModel
    {
        public AthleteModel Athlete { get; set; }
        public List<AthleteModel> Athletes { get; set; } = new List<AthleteModel>();
        public List<CountryModel> Countries { get; set; } = new List<CountryModel>();
        public List<SportModel> Sports { get; set; } = new List<SportModel>();  
    }

}

Olympics/Olympics/Models/SportModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Olympics.Models
{
    public class SportModel
    {
        public int Id { get; set; }
        public string SportName { get; set; }
        public bool TeamActivity { get; set; }
        public List<string> TeamActivityProperties { get; set; } = new List<string>() { "Team", "Non-team" };
    }
}

Olympics/Olympics/Controllers/AthleteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Olympics.Models;
using Olympics.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Olympics.Controllers
{
    public class AthleteController : Controller
    {
    
        private readonly AthleteDBService _athleteDBService;
        private readonly ParticipantsService _participantsService;


        public AthleteController(AthleteDBService athleteDBService, ParticipantsService viewsParticipantsService)
        {
            _athleteDBService = athleteDBService;
            _participantsService = viewsParticipantsService;

        }

        public IActionResult Index()
        {
            ParticipantsModel data = _participantsService.GetParticipantsDBData();
            return View(data);
        }

     
        public IActionResult Create()
        {
            ParticipantsModel data = _participantsService.GetParticipantsDBData();
            return View(data);
        }

        [HttpPost]
        public IActionResult Create(List<AthleteModel> athlete)
        {
            _athleteDBService.CreateAthlete(athlete[0]);

            return RedirectToAction("Index");
        }

        
    }
}

Olympics/Olympics/Controllers/CoutryController.cs
using Microsoft.AspNetCore.Mvc;
using Olympics.Models;
using Olympics.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Olympics.Controllers
{
    public class CountryController : Controller
    {
        private readonly CountryDBService _countryDBService;

        public CountryController(CountryDBService countryDBService)
        {
            _countryDBService = countryDBService;
        }

        public IActionResult Index()
        {
            List<CountryModel> data = _countryDBService.Read();
            return View(data);
        }

        public IActionResult Submit(CountryModel model)
        {
            _countryDBService.Create(model);
            List<CountryModel> data = _countryDBService.Read();
            return View("Index", data);
        }

        public IActionResult Create()
        {
            return View();
        }
    }
}

Olympics/Olympics/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Olympics.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Olympics.Controllers
{
    public class HomeController : Controller
    {
        private SqlConnection _connection;

        public HomeController(SqlConnection connection)
        {
            _connection = connection;
        }

        public IActionResult Index()
        {
            string connectionString = "Server=.\\MSSQLSERVER01;Database=Olympics;Integrated Security=SSPI;";
            SqlConnection connection = new SqlConnection(connectionString);

            connection.Open();

            using var command = new SqlCommand("SELECT * FROM Athletes;", connection);
            using var reader = command.ExecuteReader();
            
            while (reader.Read())
            {
                int id = reader.GetInt32(0);
            }

            connection.Close();

            return View();
        }






        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Olympics/Olympics/Controllers/SportsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Olympics.Controllers
{
    public class SportsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Olympics/Olympics/Views/Athletes/Create.cshtml
@model ParticipantsModel

<h3>Create new athlete</h3>

@using (Html.BeginForm("Submit", "Athlete", FormMethod.Post))
{
    <div class="container-full" style="background-color:aliceblue">
        <div class="container">
            @Html.LabelFor(x => x.Athlete.Name)
            @Html.TextBoxFor(x => x.Athlete.Name)
            @Html.LabelFor(x => x.Athlete.Surname)
            @Html.TextBoxFor(x => x.Athlete.Surname)
            @Html.DropDownListFor(x => x.Countries[0].Name, new SelectList(Model.Countries, "Name", "Name"))
            @Html.DropDownListFor(x => x.Sports[0].SportName, new SelectList(Model.Sports, "Name", "Name"))
            <input type="submit" value="Submit" />
        </div>
    </div>
}

@Html.ValidationSummary()

Olympics/Olympics/Views/Athletes/Index.cshtml
@model ParticipantsModel

<h3>Athletes</h3>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col">Country</th>
            <th scope="col">Sports</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Athletes)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Surname</td>
                <td>@item.CountryName</td>
                <td>
                    @foreach (var sports in item.Sports)
                    {
                        <ul>@sports</ul>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Olympics/Olympics/Views/Countries/Create.cshtml
@model CountryModel

<h5>Create new country</h5>

@using (Html.BeginForm("Submit", "Country", FormMethod.Post))
{
    <div class="container-full" style="background-color:aliceblue">
        <div class="container">
            @Html.LabelFor(x => x.Name)
            @Html.TextBoxFor(x => x.Name)
            @Html.LabelFor(x => x.ISO3)
            @Html.TextBoxFor(x => x.ISO3)
            <input type="submit" value="Submit" />
        </div>
    </div>
}

@Html.ValidationSummary()

Olympics/Olympics/Views/Countries/Index.cshtml
@model List<CountryModel>

<div class="container">
    <h1 class="mb-5">List of all athletes</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.Id</th>
                    <td>@item.CountryName</td>
                </tr>
            }
        </tbody>
    </table>

    <div>
        @Html.ActionLink("Add country", "NewCountry")
    </div>
</div>

Olympics/Olympics/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Olympics/Olympics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Olympics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Olympics</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Create
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-area="" asp-controller="Athlete" asp-action="Create">Create Athlete</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Sports" asp-action="Create">Create Sport</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Country" asp-action="Create">Create Country</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Athlete" asp-action="Index">Athletes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sports" asp-action="Index">Sports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Countries</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Olympics - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Olympics/Olympics/Views/Sports/Create.cshtml
@model SportModel

<h5>Create new sport</h5>

@using (Html.BeginForm("Submit", "Sports", FormMethod.Post))
{
    <div class="container-full" style="background-color:aliceblue">
        <div class="container">
            @Html.LabelFor(x => x.SportName)
            @Html.TextBoxFor(x => x.SportName)
            @Html.LabelFor(x => x.TeamActivity)
            @Html.TextBoxFor(x => x.TeamActivity)
            <input type="submit" value="Submit" />
        </div>
    </div>
}

@Html.ValidationSummary()

Olympics/Olympics/Views/Sports/Index.cshtml
@model List<SportModel>

<h3>Sports</h3>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">TeamActivity</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.SportName</td>
                <td>@item.TeamActivity</td>
            </tr>
        }
    </tbody>
</table>